version: '2'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "4000:4000"
    links:
      - mongodb
    command: [npm, start]
  mongodb:
    image: mongo:3
    volumes:
      - ./runtime/mongo:/data/db
    ports:
      - "27017:27017"
  rockmongo:
    image: javierjeronimo/rockmongo
    links:
      - mongodb:mongo
    ports:
      - "8081:80"
  docs:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:4000/swagger/docs/api.json
